# Generated by Django 4.1.2 on 2022-11-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='max_people',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='events',
            constraint=models.CheckConstraint(check=models.Q(('max_people__gte', 1), ('max_people__lte', 12)), name='Max people for an event can only be upto 11'),
        ),
    ]
