# Generated by Django 4.1.2 on 2022-11-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0004_alter_event_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
    ]
